name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      desktop: ${{ steps.filter.outputs.desktop }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            desktop:
              - 'apps/desktop/**'
              - 'package.json'
              - 'pnpm-lock.yaml'
              - 'turbo.json'

  build-desktop:
    needs: changes
    if: ${{ needs.changes.outputs.desktop == 'true'}}
    runs-on: ubuntu-latest
    # ビルドしたイメージを使用
    container:
      image: ghcr.io/${{ github.repository_owner }}/tauri-ci:latest
      options: --pull always
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Force Rust Environment
        run: |
          rustup default stable
          rustup update stable
          rustc --version
          cargo --version

      - name: Rust Cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "apps/desktop/src-tauri -> target"

      - name: Install dependencies
        run: pnpm install
      
      - name: Build Desktop
        env:
          RUST_BACKTRACE: 1
          RUSTUP_HOME: /usr/local/rustup
          CARGO_HOME: /usr/local/cargo
        run: |
          rustup default stable
          pnpm turbo build --filter=frontend
          pnpm turbo build --filter=desktop --verbose